---
title: "Avances LAPOP"
author: "José Rodríguez de la Fuente - Gonzalo Assusa"
date: "`r Sys.Date()`"
output: word_document
---

```{r librerias y base, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(dpi = 300)

rm(list = ls())

if (!require("pacman")) install.packages("pacman") 

pacman::p_load(tidyverse, kableExtra, janitor, readxl, gtsummary, VIM)

load("bases/lapop2004_2018.RData")

# Filtro países
lapop2004_2018 <- lapop2004_2018 %>% 
  filter(country %in% c(1, 8, 11, 13, 14, 15, 17) & wave >= 2008)

#Bases contextuales
paises_desempleo <- read_excel("bases/datos_agregados.xlsx", sheet = "Desempleo")
paises_informalidad <- read_excel("bases/datos_agregados.xlsx", sheet = "Informalidad")
paises_empleopub <- read_excel("bases/datos_agregados.xlsx", sheet = "Empleo público")
paises_brecha <- read_excel("bases/datos_agregados.xlsx", sheet = "Brecha remun")

agregados <- paises_desempleo %>% 
  left_join(paises_informalidad, by = c("country_f", "wave")) %>% 
  left_join(paises_empleopub, by = c("country_f", "wave")) %>% 
  left_join(paises_brecha, by = c("country_f", "wave")) %>% 
  mutate(wave = ifelse(wave == 2013 & country_f != "Chile", 2012, wave),
         wave = case_when(country_f == "Chile" & wave == 2006 ~ 2008,
                          country_f == "Chile" & wave == 2009 ~ 2010,
                          country_f == "Chile" & wave == 2011 ~ 2012,
                          country_f == "Chile" & wave == 2013 ~ 2014,
                          country_f == "Chile" & wave == 2015 ~ 2016,
                          country_f == "Chile" & wave == 2017 ~ 2018,
                          TRUE ~ wave)) %>% 
  filter(wave >= 2008)

```

# Preparación de la base

```{r prepación variables, echo=F, warning=F, message=F}

#2008-2018
lapop2004_2018$democracia7 <- lapop2004_2018$ing4
lapop2004_2018$democracia_ord <- lapop2004_2018$pn4
lapop2004_2018$reduc_desigualdad <- lapop2004_2018$ros4

lapop2004_2018$country_f <- factor(lapop2004_2018$country, 
                                   labels = c("México", "Colombia", "Perú", 
                                              "Chile", "Uruguay", "Brasil", "Argentina"))

lapop2004_2018$sexo <- factor(lapop2004_2018$q1, labels = c("Varón", "Mujer"))

lapop2004_2018 <- lapop2004_2018 %>% 
  mutate(categoria_ocup = case_when((colocup4a <= 2 | ocup4a <= 2) & ocup1a == 3 ~ 1,
                                  (colocup4a <= 2 | ocup4a <= 2) & ocup1a == 1 ~ 2,
                                  (colocup4a <= 2 | ocup4a <= 2) & ocup1a == 2 ~ 3,
                                  (colocup4a <= 2 | ocup4a <= 2) & ocup1a == 4 ~ 4,
                                  (colocup4a == 3 |ocup4a == 3) | ocup1a == 5 ~ 5,
                                  colocup4a >= 4 |ocup4a >= 4 ~ 6),
         categoria_ocup_f = factor(categoria_ocup, labels = c("Patrón", "Asalariado público",
                                                          "Asalariado privado",
                                                          "Cuenta propia", "Desocupado",
                                                          "Inactivo")),
         ing_decil = case_when(wave == 2008 | wave == 2010 ~ q10,
                               wave == 2012 ~ q10new_12,
                               wave == 2014 ~ q10new_14,
                               wave == 2016 ~ q10new_16,
                               wave == 2018 ~ q10new_18),
         ideologia = car::recode(l1, "1=10; 2=9; 3=8; 4=7; 5=6; 6=5; 7=4; 8=3; 9=2; 10=1"))

#2018
lapop2004_2018$desempleados <- lapop2004_2018$redist3
lapop2004_2018$desempleados <- car::recode(lapop2004_2018$desempleados,
                                           "7=1;6=2;5=3;4=4;3=5;2=6;1=7")

lapop2004_2018$ayuda_pobres <- lapop2004_2018$redist1

lapop2004_2018 <- lapop2004_2018 %>%
  mutate(redist2_inv = ifelse(wave == 2018, car::recode(redist2, "1=7; 2=6; 3=5; 4=4; 5=3; 
                                                        6=2; 7=1"), NA),
         impuestos_ricos = ifelse(wave == 2018, case_when(country == 8 ~ redist2_inv,
                                     TRUE ~ redist2a), NA),
         urbano = ifelse(wave == 2018, factor(ur, labels = c("Urbano", "Rural")), NA),
         informal = ifelse(wave == 2018, car::recode(formal, "1=0; 2=1"), NA),
         formal_f = ifelse(wave == 2018, factor(formal, labels = c("formal", "informal")), NA),
         formal_estado = factor(ifelse(wave == 2018, case_when(formal == 1 ~ 1,
                                   formal == 2 ~ 2,
                                   categoria_ocup == 5 ~ 3,
                                   categoria_ocup == 6 ~ 4,
                                   TRUE ~ NA_real_), NA)),
         formal_estado = factor(formal_estado, labels = c("Formal", "Informal", "Desocupado",
                                                          "Inactivo")),
         formal_estado2 = factor(ifelse(wave == 2018, case_when(formal == 1 ~ 1,
                                   formal == 2 ~ 2,
                                   categoria_ocup >= 5 ~ 3,
                                   TRUE ~ NA_real_), NA)),
         formal_estado2 = factor(formal_estado2, labels = c("Formal", "Informal", "No ocupados")),
         estatus_ocup = ifelse(wave == 2018, case_when(ocupoit <= 2 ~ 1,
                                  ocupoit > 2 & ocupoit < 4 ~ 2,
                                  ocupoit %in% c(5, 7, 8, 10) ~ 3,
                                  ocupoit %in% c(6, 9) ~ 4,
                                  categoria_ocup >= 5 ~ 5,
                                  TRUE ~ NA_real_), NA),
         estatus_ocup_f = factor(estatus_ocup, labels =
                                                        c("Directivos-Profesionales",
                                                          "Técnicos-administrativos-vendedores",
                                                          "Trabajadores manuales calificados",
                                                          "Trabajadores manuales no calificados",
                                                          "No ocupados")))

#Pegado bases

lapop2004_2018 <- lapop2004_2018 %>% 
  left_join(agregados, by = c("country_f", "wave"))

rm(paises_brecha, paises_desempleo, paises_empleopub, paises_informalidad)
 
```


```{r Imputación ideologia, echo=FALSE, warning=FALSE, message=FALSE}
#Random Hot Deck para la variable ideologia -----

lapop2004_2018$ideologia_imp <- lapop2004_2018$ideologia

set.seed(971986)
lapop2004_2018 <- lapop2004_2018 %>%
  hotdeck(variable = "ideologia_imp",
          domain_var = "ing_decil",
          imp_suffix = "check")
```


# Descriptivos

## Tablas resumen 

```{r tablas, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}
variables_seleccion <- lapop2004_2018 %>% 
  select(democracia7, reduc_desigualdad, desempleados, ayuda_pobres, impuestos_ricos,
         categoria_ocup_f, formal_estado, estatus_ocup_f, ideologia_imp, sexo, 
         q2, ed, urbano, desempleo, informalidad, empleo_publico, brecha_remun, country_f,
         wave)

variables_seleccion$informalidad <- variables_seleccion$informalidad * 100
variables_seleccion$desempleo <- variables_seleccion$desempleo * 100
variables_seleccion$empleo_publico <- variables_seleccion$empleo_publico * 100
variables_seleccion$brecha_remun <- variables_seleccion$brecha_remun * 100

theme_gtsummary_language("es")

variables_seleccion %>%
  tbl_summary(by = wave,
              type = list(c(democracia7, reduc_desigualdad, 
                          desempleados, ayuda_pobres,
                          impuestos_ricos) ~ "continuous"),
              label = c(democracia7 ~ "Acuerdo con democracia", 
                           reduc_desigualdad ~ "Acuerdo con políticas de 
                           reducción de desigualdad", 
                          desempleados ~ "Desempleo como fenómeno voluntario",
                          ayuda_pobres ~ "Los gobiernos deben invertir en ayudar 
                          a los pobres",
                          impuestos_ricos ~ "Injusto que los ricos paguen altos
                          impuestos",
                          categoria_ocup_f ~ "Categoría ocupacional",
                          formal_estado ~ "Formalidad",
                          estatus_ocup_f ~ "Estatus ocupacional",
                          ideologia_imp ~ "Ideología (der-izq)",
                          sexo ~ "Sexo",
                          q2 ~ "Edad",
                          ed ~ "Años educativos",
                          urbano ~ "Región",
                          desempleo ~ "Nivel de desempleo",
                          informalidad ~ "Nivel de informalidad",
                          empleo_publico ~ "Nivel de empleo público",
                          brecha_remun ~ "Brecha informales / asalariados reg.",
                          country_f ~ "País"
                          ),
                 statistic = list(all_continuous() ~ "{mean} ({sd})", 
                                  all_categorical() ~ "{n} ({p}%)"),
                 digits = list(all_categorical() ~ c(0, 1)),
  							 missing = "no") %>% 
  add_overall(col_label = "**Total**", last = TRUE) %>% 
  as_flex_table()
```

